services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: loadlens
      POSTGRES_PASSWORD: loadlens
      POSTGRES_DB: loadlens
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
